version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com'
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          region: ${AWS_DEFAULT_REGION}
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=latest'
          container-env-var-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_COGNITO_DOMAIN,value=${SERVICE_AWS_COGNITO_DOMAIN},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_ACCESS_KEY,value=${SERVICE_AWS_ACCESS_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_SECRET_KEY,value=${SERVICE_AWS_SECRET_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_S3_BUCKET_NAME,value=${SERVICE_AWS_S3_BUCKET_NAME},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_COGNITO_REGION,value=${SERVICE_AWS_COGNITO_REGION},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_COGNITO_POOL_ID,value=${SERVICE_AWS_COGNITO_POOL_ID},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=AWS_COGNITO_CLIENT_ID,value=${SERVICE_AWS_COGNITO_CLIENT_ID},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=MAILERLITE_API_KEY,value=${SERVICE_MAILERLITE_API_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=MAILERLITE_WEB_GROUP_ID,value=${SERVICE_MAILERLITE_WEB_GROUP_ID},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=MAILERLITE_NEWSLETTER_GROUP_ID,value=${SERVICE_MAILERLITE_NEWSLETTER_GROUP_ID},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=SEGMENT_WRITE_KEY,value=${SERVICE_SEGMENT_WRITE_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=HERE_MAPS_APP_ID,value=${SERVICE_HERE_MAPS_APP_ID},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=HERE_MAPS_API_KEY,value=${SERVICE_HERE_MAPS_API_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=SENTRY_DSN,value=${SERVICE_SENTRY_DSN}'
