const CUSTOM_ATTRIBUTE_PREFIX = 'custom:';
const ROLE_ATTRIBUTE = `${CUSTOM_ATTRIBUTE_PREFIX}role`;

const FORCE_CHANGE_PASSWORD_STATUS = 'FORCE_CHANGE_PASSWORD';

const NOT_AUTHORIZED = 'NotAuthorizedException';
const FORCE_CHANGE_PASSWORD = 'ForceChangePasswordException';

module.exports = {
  CUSTOM_ATTRIBUTE_PREFIX,
  ROLE_ATTRIBUTE,
  FORCE_CHANGE_PASSWORD_STATUS,
  NOT_AUTHORIZED,
  FORCE_CHANGE_PASSWORD,
};
