const CUSTOM_ATTRIBUTE_PREFIX = 'custom:';
const ROLE_ATTRIBUTE = `${CUSTOM_ATTRIBUTE_PREFIX}role`;

const FORCE_CHANGE_PASSWORD_STATUS = 'FORCE_CHANGE_PASSWORD';

const NOT_AUTHORIZED = 'NotAuthorizedException';
const FORCE_CHANGE_PASSWORD = 'ForceChangePasswordException';
const NOT_SIGNED_UP = 'NotSignedUpException';
const ALREADY_SIGNED_UP = 'AlreadySignedUpException';

module.exports = {
  CUSTOM_ATTRIBUTE_PREFIX,
  ROLE_ATTRIBUTE,
  FORCE_CHANGE_PASSWORD_STATUS,
  NOT_AUTHORIZED,
  FORCE_CHANGE_PASSWORD,
  NOT_SIGNED_UP,
  ALREADY_SIGNED_UP,
};
