const SHARED_TRIP_TYPE = 'SHARED_TRIP';
const SAVED_TRIP_TYPE = 'SAVED_TRIP';

const PLANNED_TRIP_STATUS = 'PLANNED';
const IN_PROGRESS_TRIP_STATUS = 'IN_PROGRESS';
const FINISHED_TRIP_STATUS = 'FINISHED';

module.exports = {
  SHARED_TRIP_TYPE,
  SAVED_TRIP_TYPE,
  PLANNED_TRIP_STATUS,
  IN_PROGRESS_TRIP_STATUS,
  FINISHED_TRIP_STATUS,
};
